name = "BEASTPlus"
uuid = "e2d8266a-d851-4f32-9558-488e5bc11105"
authors = ["Paul-Olyslager"]
version = "1.0.0-DEV"

[deps]
BEAST = "bb4162c7-ba94-5a20-af32-d8ec4428bdd1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BEAST = "2.5.0"
LinearAlgebra = "1.11.0"
SparseArrays = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
